# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "CodeCraft:<br>Authored by Human, Refined by AI"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  "CodeCraft: Where cutting-edge AI meets my personal journey through the ever-evolving world of software engineering. This blog is my platform for sharing the latest trends, insights, and reflections on navigating the complexities of coding and development. Each post, while initially AI-powered, is carefully crafted and finalized with a human touch, reflecting a blend of technological innovation and seasoned expertise. Join me in exploring the challenges and triumphs of software engineering as we learn, grow, and innovate together."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rafaltruszkowski.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: "truszko1/minimal-mistakes@1.3"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-K64LF9T353"
    anonymize_ip: false # default'

permalink: /:title

comments: true